# Generated by Django 5.1 on 2024-09-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_allfieldtype_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Sr_NO', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('joining_date', models.DateField()),
                ('service_year', models.DurationField()),
                ('permenent', models.BooleanField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
