# Generated by Django 5.1 on 2024-09-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('Sr_NO1', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_salary', models.BigIntegerField()),
                ('compensation', models.BigIntegerField()),
                ('stipend', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary_record',
            fields=[
                ('Sr_NO2', models.AutoField(primary_key=True, serialize=False)),
                ('salary1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.salary')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.teacher')),
            ],
        ),
    ]
