# Generated by Django 5.1 on 2024-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0005_salary_salary_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='compensation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='monthly_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='stipend',
            field=models.IntegerField(),
        ),
    ]
