# Generated by Django 5.1 on 2024-09-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0006_alter_salary_compensation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_record',
            name='salary1',
        ),
        migrations.RemoveField(
            model_name='salary_record',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='Salary_record',
        ),
    ]
