# Generated by Django 5.1 on 2024-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_salaryrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
