# Generated by Django 5.1 on 2024-09-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0009_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_r', to='arts.salary'),
        ),
    ]
