# Generated by Django 5.1 on 2024-09-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0010_salaryrecord_salary_student_count_alter_student_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='count',
        ),
    ]
