# Generated by Django 5.1 on 2024-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0012_remove_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('genre', models.TextField(blank=True)),
                ('release_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
