# Generated by Django 5.1 on 2024-10-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0013_moviecollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrecord',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
    ]
