# Generated by Django 5.1 on 2024-09-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixapp', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
    ]
